[package]
name = "morq"
version = "0.2.1"
homepage = "http://morq.rs"
repository = "https://github.com/afshinm/morq"
description = "TDD/BDD assertion interface"
license = "MIT"
authors = ["Afshin Mehrabani <afshin.meh@gmail.com>"]

[dependencies]
num = "0.1.40"
